Itheum/data-dex

src/AdvertisedData.js, src/App.js, src/BuyData.js, src/ChainTransactions.js, src/DataCoalition/DataCoalitionsViewAll.js, src/DataCoalitions.js, src/DataNFT/DataNFTMarketplace.js, src/DataNFT/MyDataNFTs.js, src/DataVault.js, src/PersonalDataProofs.js, src/PurchasedData.js, src/SellData.js, src/Tools.js, src/UtilComps/AlertOverlay.js, src/UtilComps/ClaimModal.js, src/index.js, src/libs/contactAddresses.js, src/libs/contexts.js, src/libs/util.js, src/store/ChainMetaContext.js, src/store/UserContext.js
Work complete on https://github.com/Itheum/data-dex/issues/67
=> Feature/#67 claims portal 

src/App/AppMultiversX.js
=> Active tab highlighted

src/AdvertiseData/SellDataMultiversX.js, src/App/AppMultiversX.js, src/DataNFT/MyDataNFTsMultiversX.tsx, src/Launch/AuthLauncher.js
=> Minor changes

package.json, src/Sections/AppFooter.tsx, src/index.tsx, src/libs/util2.tsx
Do not merge and close until team discussion.
=> FEATURE > STG

src/components/Sections/AppFooter.tsx, src/pages/App/AuthPickerMultiversX.tsx
=> new privacy policy link

src/libs/utils/util.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/store/StoreProvider.tsx
Offer page and component done #769 issue
=> D enciu backend

src/pages/DataNFT/DataNFTDetails.tsx
I've made the changes for the data nft page when it's a drawer and when it's a full page and also fixed and error message that made the upper buttons to jump when the error appear.
=> fixed a jumping error message + redirect pages

src/pages/DataNFT/DataNFTDetails.tsx
Fixed the filter of view offer. If you view an offer it won't show in the table of offers.
=> fixed the filter of view offer

package-lock.json, package.json, src/components/Tables/TokenTxTable.tsx, src/components/UtilComps/AppSettings.tsx, src/components/WalletDataNFTMX.tsx, src/libs/MultiversX/dataNftMarket.ts, src/libs/language.ts, src/libs/utils/util.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/GetWhitelist/index.tsx, src/pages/LandingPage/index.tsx, src/store/StoreProvider.tsx
Fixes all issue where mainnet version not working for non-logged in users.
=> 1.2.0 Hotfix > STG

src/components/MarketplaceLowerCard.tsx, src/components/WalletDataNFTMX.tsx, src/libs/config.ts, src/pages/App/Launcher.tsx
- [] Did you test your changes in logged out, mainnet logged in and devnet logged in modes?
- [] Did you test your changes in mobile, tablet and desktop modes?
- [] Did you test your changes with or without the Itheum Web2 API availability? (don't forget about "graceful fallback")
- [] Did you use reasonable user alearts and error messages? (and put them in language.ts)
- [] Did you leave the code base cleaner than you found it overall (done reasonable refactoring efforts wherever you felt that was needed)?
=> D stg kent

src/components/Sections/RecentDataNFTs.tsx, src/libs/utils/util.ts, src/pages/App/AppHarnessMultiversX.tsx, src/pages/App/AppMultiversX.tsx, src/store/StoreProvider.tsx
=> routed more chainIds

src/libs/MultiversX/backend-api.ts, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/store/StoreProvider.tsx, src/store/market.ts
=> [Ice] #862

package-lock.json, package.json, src/components/Sections/AppHeader.tsx, src/pages/App/AppMultiversX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/GuardRails/GuardRails.tsx, src/pages/GuardRails/components/guardRailsCards.tsx
=> 1.3 version bump, some polish, rename guardRail route to lowercase

src/components/WalletDataNFTMX.tsx
=> [Ice] fix web-wallet signing after Guardian upgrade

src/components/MarketplaceLowerCard.tsx, src/components/MyListedDataLowerCard.tsx, src/components/MyListedDataNFT.tsx, src/components/WalletDataNFTMX.tsx, src/libs/utils/util.ts, src/pages/DataNFT/DataNFTDetails.tsx
=> preview data fix 1.4.0

src/components/WalletDataNFTMX.tsx, src/pages/DataNFT/DataNFTDetails.tsx
=> hotfix for details

package-lock.json, package.json, src/components/WalletDataNFTMX.tsx, src/libs/utils/util.ts
=> [Ice] web-wallet sign hotfix 1

package-lock.json, package.json, src/components/Sections/RecentDataNFTs.tsx, src/components/WalletDataNFTMX.tsx, src/libs/utils/util.ts, src/pages/DataNFT/DataNFTDetails.tsx
=> [Ice] web-wallet hotfix 1

package-lock.json, package.json, src/components/ClaimModal/ClaimModalMultiversX.tsx, src/components/MarketplaceLowerCard.tsx, src/components/Sections/AppFooter.tsx, src/components/Sections/AppHeader.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/Tables/ClaimsTxTable.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/UtilComps/DataNFTLiveUptime.tsx, src/components/UtilComps/ExploreAppButton.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/components/WalletDataNFTMX.tsx, src/libs/MultiversX/custom.css, src/libs/config.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/MintDataMultiversX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/GuardRails/GuardRails.tsx, src/pages/Home/HomeMultiversX.tsx, src/pages/Profile/components/DataCreatorInfo.tsx
=> d-damian 1.4.0 INCLUDES 1.3.0 MERGE

src/components/Sections/AppHeader.tsx, src/components/Sections/ExplainerArticles.tsx, src/libs/config.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/GuardRails/GuardRails.tsx
=> Revert "1.3.4> Milesone 1.4.0 : Hotfix 922 new app support"

package-lock.json, package.json, src/pages/DataNFT/DataNFTDetails.tsx
=> 1.3.5 Hotfix : #934 preview data button fix for non logged in view

src/components/WalletDataNFTMX.tsx, src/libs/utils/util.ts, src/pages/App/AppMultiversX.tsx
=> [Ice] #931

src/pages/App/AppHarnessMultiversX.tsx
=> solved constant page redirect

src/components/ListDataNFTModal.tsx, src/components/ProcureDataNFTModal.tsx
The mvx index event is not always on the results[0]
=> fix: index is taken from mvx api event response

src/pages/Profile/components/DataCreatorTabs.tsx
=> listed data count on profile it's correct now

src/components/ProfileCard.tsx, src/libs/language.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/Profile/components/DataCreatorTabs.tsx, src/store/StoreProvider.tsx
=> [Ice] #948

src/pages/Profile/components/DataCreatorInfo.tsx
=> fixed herotah when accessed for other address it's hidden #973

src/libs/utils/util.ts, src/pages/App/AppHarnessMultiversX.tsx, src/pages/App/Launcher.tsx
=> hub hotfix

src/components/ListDataNFTModal.tsx, src/components/MyListedDataLowerCard.tsx, src/components/ProcureDataNFTModal.tsx, src/components/WalletDataNFTMX.tsx, src/libs/MultiversX/dataNftMarket.ts, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx
=> fix: support web wallet for delist and update price

src/components/Sections/RecentDataNFTs.tsx, src/libs/utils/util.ts, src/store/StoreProvider.tsx
=> balance from mainnet

src/components/ListDataNFTModal.tsx, src/components/MyListedDataLowerCard.tsx
=> fix: buyer fee fallback if marketRequirements is not loaded

src/pages/GetWhitelist/LandingPage/LandingPage.tsx
=> fix wl page

package-lock.json, package.json, src/components/Sections/RecentArticles.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/WalletDataNFTMX.tsx, src/libs/language.ts, src/pages/AdvertiseData/MintDataMultiversX.tsx, src/pages/App/AppMultiversX.tsx, src/pages/App/AuthPickerMultiversX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx
=> 1.5.0 : native-auth, itheum-sdk v1.2.0

src/components/ListDataNFTModal.tsx, src/components/MyListedDataLowerCard.tsx, src/components/ProcureDataNFTModal.tsx, src/components/WalletDataNFTMX.tsx, src/pages/App/AuthPickerMultiversX.tsx
=> native auth fix + backend routing

package-lock.json, src/components/Sections/AppHeader.tsx, src/components/UtilComps/DataNFTLiveUptime.tsx, src/pages/App/AppMultiversX.tsx, src/pages/App/Launcher.tsx, src/pages/Home/AppMarketplace.tsx, src/pages/Home/HomeMultiversX.tsx
=> fix net separation

package-lock.json, package.json, src/libs/utils/util.ts, src/pages/AdvertiseData/MintDataMultiversX.tsx, src/pages/App/AppMultiversX.tsx
=> TEST -> STG

package-lock.json, package.json, src/components/Sections/AppHeader.tsx, src/pages/App/AppMultiversX.tsx, src/pages/App/ModalAuthPickerMultiversX.tsx, src/pages/LandingPage/index.tsx, src/store/account.ts
=> D enciu 1.7.0

package-lock.json, package.json
=> ith sdk update

src/libs/MultiversX/dataNftMarket.ts, src/pages/App/AppMultiversX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx
=> fixed gas bug + deleted logs + fixed NaN balance and total supply

src/libs/config.ts
=> nonce added for nftunes

package-lock.json, src/components/Tables/TokenTxTable.tsx
=> hot-fix: history table

package-lock.json, package.json, src/libs/contractAddresses.ts
=> new devnet contracts

package-lock.json, package.json
=> new sdk version

package-lock.json, package.json, src/libs/utils/UseWindowSize.tsx, src/pages/App/AppMultiversX.tsx, src/pages/Enterprise/Enterprise.tsx
=> Ith enterprise

package-lock.json, src/components/MyListedDataNFT.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/GuardRails/GuardRails.tsx
=> d-robert 1.8.0

package-lock.json, package.json, public/index.html, src/components/ProcureDataNFTModal.tsx, src/components/UtilComps/DataNFTLiveUptime.tsx, src/components/WalletDataNFTMX.tsx, src/libs/MultiversX/custom.css, src/libs/language.ts, src/pages/AdvertiseData/MintDataMultiversX.tsx, src/pages/App/AppMultiversX.tsx, src/pages/App/ModalAuthPickerMultiversX.tsx
=> d-damian 1.8.0

package-lock.json, src/libs/utils/number.ts, src/pages/Home/HomeMultiversX.tsx
=> Claims fix

package-lock.json, package.json, src/libs/MultiversX/api.ts, src/pages/Enterprise/Enterprise.tsx, src/pages/Enterprise/components/DataNftCollection/ClaimRoyalties.tsx, src/pages/Enterprise/components/DataNftCollection/DataNftCollection.tsx, src/pages/Enterprise/components/DataNftCollection/LiveSettings.tsx, src/pages/Enterprise/components/DataNftCollection/MintDataNft.tsx, src/pages/Enterprise/components/DataNftCollection/TransferControl.tsx, src/pages/Enterprise/components/DataNftCollection/WhitelistControl.tsx, src/pages/Enterprise/components/LaunchNftMinter.tsx, src/pages/Enterprise/components/MinterDashboard.tsx, src/store/mint.ts
=> Ith enterprise2

package-lock.json, package.json, public/index.html
=> added new cookieyes script for testing

src/components/Tables/InteractionTxTable.tsx, src/components/Tables/TokenTxTable.tsx, src/pages/DataNFT/DataNFTDetails.tsx
=> feat: NFT/SFT activity fallback if backend is down

package-lock.json, src/components/Sections/AppHeader.tsx, src/pages/App/AppMultiversX.tsx
=> d-robert 1.9.0

package-lock.json, package.json, src/libs/MultiversX/ABIs/datanftmint.abi.json
=> datanftmint new abi for smart contract v2

src/components/WalletDataNFTMX.tsx
=> hot-fix: multi token access 

package-lock.json, package.json, src/components/Sections/AppHeader.tsx, src/components/Sections/ExplainerArticles.tsx, src/components/Sections/RecentArticles.tsx, src/components/Sections/RecentDataNFTs.tsx, src/libs/config.ts, src/pages/App/ModalAuthPickerMultiversX.tsx
=> Hotfix reenable ledger + fix title and responsive style issues

package-lock.json, package.json, src/components/Sections/AppHeader.tsx, src/components/Sections/ExplainerArticles.tsx, src/components/Sections/RecentArticles.tsx, src/components/Sections/RecentDataNFTs.tsx, src/libs/config.ts, src/pages/App/ModalAuthPickerMultiversX.tsx
=> Latest main hotfix to STG

package-lock.json, package.json, src/components/Sections/AppHeader.tsx, src/components/Sections/ExplainerArticles.tsx, src/components/Sections/RecentArticles.tsx, src/components/Sections/RecentDataNFTs.tsx, src/libs/config.ts, src/pages/App/ModalAuthPickerMultiversX.tsx
=> Latest main hotfix to TEST

package-lock.json, package.json
=> updated sdk-dapp library

src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx
=> fix: group offers update

src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx
=> fix: solve pagination in my listed data nfts

package.json, src/pages/AdvertiseData/components/TradeForm.tsx
=> fix: switch data marshal api key from const

package-lock.json, package.json
=> fix: sdk data nft update new version

package-lock.json, package.json, src/components/Sections/AppFooter.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/Enterprise/Enterprise.tsx
=> d-enciu 1.11.0

package-lock.json, src/components/MarketplaceLowerCard.tsx, src/components/MyListedDataLowerCard.tsx, src/components/MyListedDataNFT.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/Profile/components/DataCreatorTabs.tsx, src/store/StoreProvider.tsx
=> d-damian 1.11.0 

package-lock.json, src/libs/utils/number.ts
=> Claims formatting fix

package.json, src/libs/config.ts
=> Add tc to main

src/pages/AdvertiseData/components/TradeFormModal.tsx
=> Add time capsule to mainnet

package-lock.json, package.json, src/components/ListDataNFTModal.tsx
=> Fix view data diff marshal

package.json, src/components/ProcureDataNFTModal.tsx
=> fix: correct marshal uptime check

src/components/MarketplaceLowerCard.tsx, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/Enterprise/components/DataNftCollection/CurateNfts.tsx
=> clear: deleted commented code + console.logs

package-lock.json, package.json, src/components/CustomPagination.tsx, src/components/ListDataNFTModal.tsx, src/components/Liveliness/LivelinessScore.tsx, src/components/MarketplaceLowerCard.tsx, src/components/MyListedDataNFT.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/libs/MultiversX/claims.ts, src/libs/MultiversX/dataNftMint.ts, src/libs/MultiversX/faucet.ts, src/libs/config.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/FavoriteCards.tsx, src/pages/Enterprise/components/DataNftCollection/CurateNfts.tsx, src/store/StoreProvider.tsx, src/store/market.ts, src/store/mint.ts
=> Milestone 1.12.0 -> TEST

package-lock.json, package.json, src/libs/utils/util.ts
=> fix: added last version of sdk + fixing on naming

package-lock.json, package.json, src/components/CustomPagination.tsx, src/components/Faucet/Faucet.tsx, src/components/ListDataNFTModal.tsx, src/components/Liveliness/LivelinessScore.tsx, src/components/MarketplaceLowerCard.tsx, src/components/MyListedDataNFT.tsx, src/components/Sections/AppHeader.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/libs/MultiversX/claims.ts, src/libs/MultiversX/dataNftMarket.ts, src/libs/MultiversX/dataNftMint.ts, src/libs/MultiversX/faucet.ts, src/libs/config.ts, src/libs/language.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/FavoriteCards.tsx, src/pages/Enterprise/components/DataNftCollection/CurateNfts.tsx, src/store/StoreProvider.tsx, src/store/market.ts, src/store/mint.ts
=> 1.12.0 TEST -> STG

package-lock.json, package.json, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx
=> feat: support ipns on data dex form

src/pages/AdvertiseData/components/TradeForm.tsx
=> fix: ipns standard

package-lock.json, package.json, src/libs/language.ts, src/pages/AdvertiseData/components/TradeForm.tsx
=> fix: sdk update && remove https err check on data stream

package-lock.json, package.json, src/components/Liveliness/LivelinessScore.tsx, src/libs/language.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/App/AppMultiversX.tsx, src/pages/Bonding/Bonding.tsx, src/pages/Bonding/components/BondingParameters.tsx, src/pages/Bonding/components/CollectionDashboard.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/store/mint.ts
=> D enciu 1.13.0

package-lock.json, package.json, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/language.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx, src/pages/Home/components/TrendingData.tsx
=> fix: allow ipfs also to the form validation

src/pages/AdvertiseData/components/TradeFormModal.tsx
=> feature: mint form allows query string dmf flag for 403 code

src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx
=> fix: quick fixes on wallet and minting form

package-lock.json, package.json, src/components/Liveliness/LivelinessScore.tsx, src/pages/AdvertiseData/TradeData.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx
=> feature: bonding details refined for final feature to go live

package-lock.json, package.json, src/components/Liveliness/LivelinessScore.tsx, src/pages/AdvertiseData/TradeData.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/AdvertiseData/components/TradeFormModal.tsx
=> HOTFIX 1.13.4: bonding details refined for final feature to go live

src/components/Sections/AppHeader.tsx, src/components/WalletDataNFTMX/AccessDatastreamModal.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/config.ts, src/libs/types.ts, src/store/StoreProvider.tsx, src/store/account.ts
=> D enciu bitz

package.json, src/components/Sections/AppHeader.tsx, src/components/WalletDataNFTMX/AccessDatastreamModal.tsx, src/pages/AdvertiseData/components/TradeForm.tsx
fix: redirect to new tab get bitz / bump version / commented trade form validation
=> feat: mobile bitz view

package.json, src/components/Sections/AppHeader.tsx, src/pages/DataNFT/DataNftCollection.tsx
=> style: fix on style and bump

package-lock.json, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx
=> fix: showing the bonding tab in wallet

src/pages/Bonding/Bonding.tsx
=> fix: total bonded

package-lock.json, package.json, src/components/MarketplaceLowerCard.tsx, src/components/Sections/AppHeader.tsx, src/components/UtilComps/ExploreAppButton.tsx, src/components/WalletDataNFTMX/AccessDatastreamModal.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/MultiversX/api.ts, src/libs/config.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx
Mega feature branch to brign xFabric minted Data NFT-PF Data NFT support that will span a few sprints. 
KEEP IN SYNC WITH ALL LATEST MILESTONES and DO NOT MERGE.
=> Feature xFabric DataNFT-PH Support

src/components/ListDataNFTModal.tsx
=> fix: live update addOffer to backend

src/components/CountDown.tsx, src/components/MarketplaceLowerCard.tsx, src/components/ProcureDataNFTModal.tsx, src/components/Sections/AppHeader.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/utils/util.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/store/StoreProvider.tsx, src/store/account.ts
=> D robert 1.14.0

package-lock.json, package.json, src/components/CountDown.tsx, src/components/ListDataNFTModal.tsx, src/components/Liveliness/LivelinessScore.tsx, src/components/MarketplaceLowerCard.tsx, src/components/ProcureDataNFTModal.tsx, src/components/Sections/AppHeader.tsx, src/components/UtilComps/ExploreAppButton.tsx, src/components/WalletDataNFTMX/AccessDatastreamModal.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/MultiversX/api.ts, src/libs/config.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/Bonding/Bonding.tsx, src/pages/Bonding/components/CollectionDashboard.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/store/StoreProvider.tsx, src/store/account.ts
=> Bonding WIP TEST -> STG

src/components/CountDown.tsx
=> fix: hours display on countdown

src/components/Sections/AppHeader.tsx, src/libs/MultiversX/custom.css
=> bubles animation for the flask

package.json, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/config.ts
=> 1.14.1 hotfix bober + marshal sdk

.gitignore, package.json, src/pages/Bonding/Bonding.tsx, src/pages/Bonding/components/BondingParameters.tsx
=> Bonding addresses & deep links PoC STG -> MAIN

package.json, src/libs/MultiversX/dataNftMint.ts, src/libs/config.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/Bonding/components/BondingParameters.tsx
=> Revert "fix: bonding DAO mainnet"

package.json, src/pages/AdvertiseData/components/MintingModal.tsx, src/pages/AdvertiseData/components/TradeForm.tsx
=> TEST -> STG fix asset upload

package.json, src/pages/AdvertiseData/components/MintingModal.tsx, src/pages/AdvertiseData/components/TradeForm.tsx
=> STG -> MAIN Fix asset upload

package.json
=> fix: pinata image upload

package.json, src/libs/config.ts
=> chore: new explore button NFTs

package.json, src/store/StoreProvider.tsx
=> feat: #1319

src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/components/BondingCards.tsx
=> fix: minting form

src/pages/Home/components/VolumesDataNfts.tsx, src/pages/LandingPage/index.tsx
=> fix: most treaded rename and show it even when the user is not logged in

src/components/ListDataNFTModal.tsx, src/components/MyListedDataLowerCard.tsx, src/components/NftMediaComponent.tsx, src/components/ProcureDataNFTModal.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/components/WalletDataNFTMX/BurnDataNFTModal.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/types.ts, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/Home/components/TrendingData.tsx, src/pages/Home/components/VolumesDataNfts.tsx
=> ipfs video media and cards overlapping on resolution change

src/components/Sections/RecentDataNFTs.tsx, src/pages/Home/components/TrendingData.tsx
=> fix: overlapping when user is logged out

src/components/Faucet/Faucet.tsx
=> fix: Faucet button text

package.json, src/components/UtilComps/DataNFTLiveUptime.tsx, src/store/StoreProvider.tsx, src/store/account.ts
=> Feat: Bitz Bonus

package.json, src/components/UtilComps/DataNFTLiveUptime.tsx, src/store/StoreProvider.tsx, src/store/account.ts
=> Feat: Bonus Bitz

package.json, src/components/Liveliness/LivelinessScore.tsx, src/libs/config.ts, src/pages/AdvertiseData/TradeData.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/DataNFT/components/LivelinessStaking.tsx
=> feat: live stake

package.json, src/pages/GetNFMeID/LandingPage/LandingPage.tsx
=> chore: add nfme solana whitelist form

package.json, src/libs/config.ts
=> chore: fix the nfme data preview issue

package.json, src/components/NftMediaComponent.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/DataNFT/components/LivelinessStaking.tsx, src/pages/Home/HomeMultiversX.tsx
=> FIX: style and typo issues fix, dashboard box fix to wrap correct, bonding time period issues

package.json, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx
=> feature: remove max per address limit by default

package.json, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx
=> feature: add back the max per address limit by default

package.json, src/components/MyListedDataNFT.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/components/BondingCards.tsx
and  align the color codes for badges across the app for creator vs owner.
=> feature: fix issue where liveliness page list of no bond data nfts were showing items the user did not create

package.json, src/components/Liveliness/LivelinessScore.tsx, src/components/ProposalButton/index.tsx, src/libs/utils/util.ts, src/pages/DataNFT/components/BondingCards.tsx
=> feature: show expiry date of current bond on liveliness bar for bonding cards only

src/components/Liveliness/LivelinessStakingSol.tsx, src/components/NftMediaComponent.tsx, src/libs/Solana/utils.ts, src/pages/AdvertiseData/components/MintingModal.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/DataNFT/components/CompensationCards.tsx
=> Before launch adjustments 

src/components/NftMediaComponent.tsx, src/components/ProfileCard.tsx, src/components/SolanaNfts/WalletDataNftSol.tsx
=> D robert sol integration

src/components/Liveliness/LivelinessStakingSol.tsx, src/components/Sections/AppHeader.tsx, src/components/SolanaNfts/WalletDataNftSol.tsx, src/components/UtilComps/ChainSupportedComponent.tsx, src/components/UtilComps/ErrorBoundary.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/Solana/utils.ts, src/pages/AdvertiseData/TradeData.tsx, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/App/App.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/DataNFT/components/LivelinessStaking.tsx, src/pages/GetBitz/GetBitzSol/index.tsx, src/pages/GetBitz/PlayBitzModal.tsx, src/pages/GetNFMeID/LandingPage/LandingPage.tsx, src/pages/Home/HomeMultiversX.tsx, src/pages/Home/components/VolumesDataNfts.tsx, src/pages/LandingPage/index.tsx, src/store/StoreProvider.tsx, tailwind.config.js
=> bugs NftMeID and UI improvements

package.json, src/components/ProcureDataNFTModal.tsx, src/components/ProcureDataNFTSuccessCTAModel.tsx, src/components/UtilComps/ExploreAppButton.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/Profile/components/DataCreatorTabs.tsx
=> feature: post purchase, show a CTA model for what they can do with their new Data NFT

package.json, src/components/ProcureDataNFTModal.tsx, src/components/ProcureDataNFTSuccessCTAModel.tsx, src/components/UtilComps/ExploreAppButton.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/LandingPage/index.tsx, src/pages/Profile/components/DataCreatorTabs.tsx
=> Feature: post-purchase, show a CTA model for what they can do with their new Data NFT

package.json, src/components/MarketplaceLowerCard.tsx, src/components/ProcureDataNFTModal.tsx, src/components/ProcureDataNFTSuccessCTAModel.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/store/StoreProvider.tsx
…screen error that came up for this use case, fixed issue with NaN royalty on list view and some other code cleanup
=> feature: procure from list view also shows CTA modal 

package.json, src/pages/DataNFT/components/FavoriteCards.tsx, src/pages/DataNFT/components/FeaturedDataNFTListings.tsx, src/pages/LandingPage/index.tsx
featured listing comp support hiding collapse option
=> feature: feature music listing deep links direct

package.json, src/libs/config.ts, src/libs/utils/util.ts, src/pages/App/ModalAuthPickerMultiversX.tsx
=> feature: login connected to new user account system

package.json, src/libs/config.ts
=> feature: increase timeout for mvx api to 20s

package.json, src/pages/AdvertiseData/components/TradeForm.tsx
=> fix: mint form lockperiod throws js error when network slow

package.json, src/libs/MultiversX/api.ts
=> fix: increase all timeout to 20s

package.json, src/components/Sections/AppHeader.tsx, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/GetNFMeID/LandingPage/LandingPage.tsx
=> feature: improve the nfmeid page for better cta

package.json, src/components/Sections/AppHeader.tsx, src/libs/MultiversX/api.ts, src/pages/DataNFT/MyDataNFTsMultiversX.tsx, src/pages/GetNFMeID/LandingPage/LandingPage.tsx
=>  improve the nfmeid page for better cta

src/components/Liveliness/LivelinessStakingSol.tsx, src/libs/Solana/utils.ts
=> Fix page to load without any active bond 

src/components/Liveliness/LivelinessStakingSol.tsx, src/libs/Solana/CoreSolBondStakeSc.ts, src/libs/Solana/types.ts, src/libs/Solana/utils.ts
=> feat: support latest changes for vault bond

src/components/Liveliness/LivelinessStakingSol.tsx
=> feat: improved UI/UX

src/components/Liveliness/LivelinessStakingSol.tsx
=> UI improvements

index.html, package.json, src/libs/MultiversX/custom.css
=> fix: comment out external code files to see if the site speeds up

package.json, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx
=> fix: roll back the last loading fix as it broke somethign else

package.json, src/components/Sections/AppFooter.tsx, src/pages/DataNFT/components/FeaturedDataNFTListings.tsx, src/pages/LandingPage/index.tsx
=> feature: added updates to featured data nft two weeks

src/libs/config.ts
=> chore: added new nftunes app nonce

src/pages/DataNFT/components/FeaturedDataNFTListings.tsx
=> chore: fixed link issue

index.html, package.json
=> feature: add back GA

index.html, package.json, src/components/ListDataNFTModal.tsx, src/components/MyListedDataNFT.tsx, src/components/ProfileCard.tsx, src/components/Sections/AppFooter.tsx, src/components/Sections/NoDataHere.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/Tables/InteractionTxTable.tsx, src/components/Tables/TokenTxTable.tsx, src/components/UtilComps/AppSettings.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/libs/MultiversX/api.ts, src/libs/utils/util.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/App/Launcher.tsx, src/pages/App/ModalAuthPickerMultiversX.tsx, src/pages/Bonding/Bonding.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/DataNFT/components/FavoriteCards.tsx, src/pages/Enterprise/components/DataNftCollection/ClaimRoyalties.tsx, src/pages/Enterprise/components/DataNftCollection/CurateNfts.tsx, src/pages/Home/components/TrendingData.tsx, src/pages/Home/components/VolumesDataNfts.tsx, src/store/StoreProvider.tsx
=> Hotfix perf upgrades nov24

package.json, src/pages/App/Launcher.tsx, src/pages/App/ModalAuthPickerMultiversX.tsx
=> fix: allow for devnet usage by check of env

package.json, src/components/Sections/AppHeader.tsx, src/components/Sections/NoDataHere.tsx, src/components/Sections/RecentDataNFTs.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/components/FeaturedDataNFTListings.tsx
=> feature: fix view offer link, let user logout

package.json, src/components/ListDataNFTModal.tsx, src/components/MarketplaceLowerCard.tsx, src/components/MyListedDataLowerCard.tsx, src/components/NftMediaComponent.tsx, src/components/ProcureDataNFTModal.tsx, src/components/ProcureDataNFTSuccessCTAModel.tsx, src/components/Sections/AppHeader.tsx, src/components/Sections/RecentDataNFTs.tsx, src/components/UtilComps/UpperCardComponent.tsx, src/components/WalletDataNFTMX/BurnDataNFTModal.tsx, src/components/WalletDataNFTMX/WalletDataNFTMX.tsx, src/pages/DataNFT/DataNFTDetails.tsx, src/pages/DataNFT/DataNFTMarketplaceMultiversX.tsx, src/pages/DataNFT/DataNftCollection.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/Home/components/TrendingData.tsx, src/pages/Home/components/VolumesDataNfts.tsx, src/pages/Profile/components/DataCreatorTabs.tsx
=> feature: fix image issues on private rpc, roll lback to sdk-dapp

package.json, src/components/Tables/InteractionTxTable.tsx, src/components/Tables/TokenTxTable.tsx, src/libs/MultiversX/api.ts, src/libs/utils/util.ts
=> feature: cache the beavy transaction calls

package.json, src/components/BuyItheumModal.tsx, src/components/Sections/AppHeader.tsx, src/libs/language.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/DataNFTDetails.tsx
=> feature: put the buy ITH modal everywhere where we say ITH is not enough

package.json, src/components/BuyItheumModal.tsx
=> fix: use debounced amount

package.json, src/libs/config.ts, src/pages/AdvertiseData/components/TradeForm.tsx, src/pages/DataNFT/components/BondingCards.tsx, src/pages/DataNFT/components/LivelinessStaking.tsx
=> roll down stg
